# Jekyll Resume Theme

# Site settings
title: Phan Huy Anh
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Matt Couchman
job: front end engineer
location: Birmingham, UK
languages: HTML, CSS and Javascript
twitter_username: mattcouchman
github_username:  mattcouchman
codepen_username:  mattcouchman
email_address: phanhuyanh251@gmail.com

# Build settings
markdown: kramdown
