# Jekyll Resume Theme

# Site settings
title: Phan Huy Anh
email: email@domain.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mattcouchman.co.uk/jekyll-resume"
name: Phan Huy Anh
job: front end engineer
location: Hà Nội, VN
languages: HTML, CSS and Javascript
github_username:  phanhuyanh
codesignal_username: pain
email_address: phanhuyanh251@gmail.com

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman